### ISSUE TITLE
Error occuring during Deployment, failing during the start.sh script

### ISSUE THREAD

**Issue by ryanhachtel** [edgedb/remix#2]
Issue:
During the deployment process for the Remix application on Fly.io, an error is occurring during the `sh start.sh`. Here is the error I'm seeing from the logs.

```
 2022-11-23T19:22:59.403 runner[4091cd47] sea [info] Starting instance

2022-11-23T19:23:00.321 runner[4091cd47] sea [info] Configuring virtual machine

2022-11-23T19:23:00.322 runner[4091cd47] sea [info] Pulling container image

2022-11-23T19:23:00.735 runner[4091cd47] sea [info] Unpacking image

2022-11-23T19:23:00.751 runner[4091cd47] sea [info] Preparing kernel init

2022-11-23T19:23:01.066 runner[4091cd47] sea [info] Configuring firecracker

2022-11-23T19:23:01.252 runner[4091cd47] sea [info] Starting virtual machine

2022-11-23T19:23:01.479 app[4091cd47] sea [info] Starting init (commit: 81d5330)...

2022-11-23T19:23:01.523 app[4091cd47] sea [info] Preparing to run: `sh start.sh` as root

2022-11-23T19:23:01.562 app[4091cd47] sea [info] 2022/11/23 19:23:01 listening on [fdaa:0:e601:a7b:2c60:4091:cd47:2]:22 (DNS: [fdaa::3]:53)

2022-11-23T19:23:01.575 app[4091cd47] sea [info] + edgedb migrate

2022-11-23T19:23:03.750 app[4091cd47] sea [info] [2022-11-23T19:23:03Z WARN edgedb::version_check] Cannot check for updates: failed to fetch JSON at URL: https://packages.edgedb.com/archive/.jsonindexes/x86_64-unknown-linux-musl.json: error sending request for url (https://packages.edgedb.com/archive/.jsonindexes/x86_64-unknown-linux-musl.json): error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921: (unable to get local issuer certificate): error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921: (unable to get local issuer certificate): error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921: (unable to get local issuer certificate): error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921:

2022-11-23T19:23:04.755 app[4091cd47] sea [info] Connecting to an EdgeDB instance at newworldmerchanttool-edgedb.internal:8080...

2022-11-23T19:23:06.704 app[4091cd47] sea [info] edgedb error: InternalServerError:

2022-11-23T19:23:06.704 app[4091cd47] sea [info] Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md

2022-11-23T19:23:06.704 app[4091cd47] sea [info] Server traceback:

2022-11-23T19:23:06.707 app[4091cd47] sea [info] Traceback (most recent call last):

2022-11-23T19:23:06.707 app[4091cd47] sea [info] File "edb/server/pgcon/pgcon.pyx", line 2162, in wait_for_message

2022-11-23T19:23:06.707 app[4091cd47] sea [info] ConnectionAbortedError

2022-11-23T19:23:06.707 app[4091cd47] sea [info] During handling of the above exception, another exception occurred:

2022-11-23T19:23:06.707 app[4091cd47] sea [info] Traceback (most recent call last):

2022-11-23T19:23:06.707 app[4091cd47] sea [info] File "edb/server/protocol/binary.pyx", line 1304, in edb.server.protocol.binary.EdgeConnection.main

2022-11-23T19:23:06.707 app[4091cd47] sea [info] File "edb/server/protocol/binary.pyx", line 474, in auth

2022-11-23T19:23:06.707 app[4091cd47] sea [info] File "edb/server/protocol/binary.pyx", line 586, in _start_connection

2022-11-23T19:23:06.707 app[4091cd47] sea [info] File "/usr/lib/x86_64-linux-gnu/edgedb-server-2/lib/python3.10/site-packages/edb/server/server.py", line 544, in new_dbview

2022-11-23T19:23:06.707 app[4091cd47] sea [info] await db.introspection()

2022-11-23T19:23:06.707 app[4091cd47] sea [info] File "edb/server/dbview/dbview.pyx", line 261, in introspection

2022-11-23T19:23:06.707 app[4091cd47] sea [info] File "edb/server/dbview/dbview.pyx", line 263, in edb.server.dbview.dbview.Database.introspection

2022-11-23T19:23:06.707 app[4091cd47] sea [info] File "/usr/lib/x86_64-linux-gnu/edgedb-server-2/lib/python3.10/site-packages/edb/server/server.py", line 711, in introspect_db

2022-11-23T19:23:06.707 app[4091cd47] sea [info] user_schema = await self.introspect_user_schema(conn)

2022-11-23T19:23:06.707 app[4091cd47] sea [info] File "/usr/lib/x86_64-linux-gnu/edgedb-server-2/lib/python3.10/site-packages/edb/server/server.py", line 657, in introspect_user_schema

2022-11-23T19:23:06.707 app[4091cd47] sea [info] json_data = await conn.sql_fetch_val(self._local_intro_query)

2022-11-23T19:23:06.707 app[4091cd47] sea [info] File "edb/server/pgcon/pgcon.pyx", line 1152, in sql_fetch_val

2022-11-23T19:23:06.707 app[4091cd47] sea [info] File "edb/server/pgcon/pgcon.pyx", line 1137, in sql_fetch

2022-11-23T19:23:06.707 app[4091cd47] sea [info] File "edb/server/pgcon/pgcon.pyx", line 1076, in parse_execute

2022-11-23T19:23:06.707 app[4091cd47] sea [info] File "edb/server/pgcon/pgcon.pyx", line 1059, in _parse_execute

2022-11-23T19:23:06.707 app[4091cd47] sea [info] File "edb/server/pgcon/pgcon.pyx", line 586, in wait_for_sync

2022-11-23T19:23:06.707 app[4091cd47] sea [info] File "edb/server/pgcon/pgcon.pyx", line 2160, in wait_for_message

2022-11-23T19:23:06.707 app[4091cd47] sea [info] ConnectionAbortedError

2022-11-23T19:23:07.541 app[4091cd47] sea [info] Starting clean up. 
```

Trouble shooting I've tried so far:
- I've doubled checked the `EDGEDB_DSN` variable
- I've made sure to persist the generated TLS certificate
- Double checked the `EDGEDB_CLIENT_TLS_SECURITY` setting is set to `insecure`

**Comment by ryanhachtel** [comment]
I went back and started from scratch again with a fresh repo and that worked. I'm not sure what I messed up the first time but if anyone runs into a similar issue try starting over again and be extremely detailed about following every step and checking spelling, etc.
